name: WakaTime Readme

on:
  schedule:
    - cron: "0 */12 * * *" # Runs every 12 hours
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: WakaTime Readme
        uses: athul/waka-readme@v1.0.2
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}

      - name: Commit and push if changed
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add README.md
          git commit -m "Updated WakaTime stats" || exit 0
          git push
